---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: zookeeper
    image: zookeeper:3.4
    command: "bin/zkServer.sh start-foreground"
    published_ports:
      - "2181"
    networks:
      - name: molecule
        aliases:
          - zookeeper
  - name: kafka1
    image: wurstmeister/kafka:0.11.0.1
    command: "start-kafka.sh"
    env:
      HOSTNAME_COMMAND: "hostname -i | cut -d' ' -f1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    published_ports:
      - "9092"
    networks:
      - name: molecule
        links:
          - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  - name: kafka2
    image: wurstmeister/kafka:0.11.0.1
    command: "start-kafka.sh"
    env:
      HOSTNAME_COMMAND: "hostname -i | cut -d' ' -f1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    published_ports:
      - "9092"
    networks:
      - name: molecule
        links:
          - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: kafka_0.11.0
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
