---
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [2-slim, 3.5-slim, 3.6-slim, 3.7-slim, 3.8-slim, 3.9-slim]

    steps:
      - uses: actions/checkout@v2
      - name: Check docker install
        run: |
          set -e
          docker info
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r test-requirements.txt
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with molecule ${{ matrix.python_version }}
        run: |
          export PYTHON_VERSION=${{ matrix.python_version }}
          export ANSIBLE_MODULE_UTILS=$PWD/module_utils
          molecule create
          molecule converge
